<script setup lang="ts">
import { onBeforeUnmount, ref, watch } from "vue";
import { Activity, BarChart3, RotateCw, ShieldCheck } from "@lucide/vue";
import IntelligenceMetaStrip from "../components/IntelligenceMetaStrip.vue";
import MemberLockedResult from "../components/MemberLockedResult.vue";
import SourceDisclosure from "../components/SourceDisclosure.vue";
import { useAuth } from "../composables/useAuth";
import { useStyleProfile } from "../composables/useStyleProfile";
import { isMemberLockedResult } from "../domain/memberVisibility";
import { formatNumber, formatWeight, valueTone } from "../utils/format";

const props = defineProps<{ code: string; refreshKey?: number }>();
const { isAuthenticated } = useAuth();
const windowSize = ref<20 | 60>(20);
const { profile, loading, error, load, abort } = useStyleProfile();
watch(() => [props.code, props.refreshKey, windowSize.value], () => void load(props.code, windowSize.value), { immediate: true });
onBeforeUnmount(abort);
</script>

<template>
  <section class="style-view">
    <header class="style-hero"><div><span>經理人風格指紋</span><h1>{{ profile?.etf.code ?? code }} {{ profile?.etf.name ?? '' }}</h1><p>只描述可由公開持股可靠計算的集中度、調整廣度、調整強度、產業輪動與持股穩定度，不評價經理人優劣。</p></div><label>計算期間<select v-model.number="windowSize"><option :value="20">20 個交易日</option><option :value="60">60 個交易日</option></select></label></header>
    <p v-if="error" class="style-error">{{ error }}</p><p v-else-if="loading && !profile" class="style-state">風格指標載入中…</p>
    <IntelligenceMetaStrip v-if="profile" :source-as-of="profile.sourceAsOf" :generated-at="profile.generatedAt" :coverage="profile.coverage" :confidence="profile.confidence" />
    <section v-if="profile" class="style-labels"><span v-for="label in profile.tendencies" :key="label">{{ label }}</span><small>中性描述，不代表績效或風險評等</small></section>
    <section v-if="profile" class="style-grid"><article><header><BarChart3 :size="19" /><b>持股集中度</b></header><strong>前 10 大 {{ formatWeight(profile.concentration.top10) }}</strong><span>前 5 大 {{ formatWeight(profile.concentration.top5) }}</span><span>HHI {{ formatNumber(profile.concentration.hhi,4) }}</span></article><MemberLockedResult v-if="!isAuthenticated || isMemberLockedResult(profile.adjustmentBreadth)" title="調整廣度已遮隱" source="style_breadth" /><article v-else><header><Activity :size="19" /><b>調整廣度</b></header><strong>日均 {{ formatNumber(profile.adjustmentBreadth.averageDailyAdjustedHoldings,1) }} 檔</strong><span>最新加碼 {{ profile.adjustmentBreadth.latest?.increased ?? '-' }}／減碼 {{ profile.adjustmentBreadth.latest?.decreased ?? '-' }}</span><span>新增 {{ profile.adjustmentBreadth.latest?.added ?? '-' }}／退出 {{ profile.adjustmentBreadth.latest?.exited ?? '-' }}</span></article><article><header><RotateCw :size="19" /><b>調整與輪動強度</b></header><strong>{{ formatNumber(profile.adjustmentIntensity,2) }}</strong><span>Σ |weight change| / 2</span><span>產業輪動 {{ formatNumber(profile.sectorRotation.intensity,2) }}</span></article><MemberLockedResult v-if="!isAuthenticated || isMemberLockedResult(profile.stability)" title="持股穩定度已遮隱" source="style_stability" /><article v-else><header><ShieldCheck :size="19" /><b>持股穩定度</b></header><strong>20 日 {{ profile.stability.retention20 === null ? '-' : formatNumber(profile.stability.retention20*100,0)+'%' }}</strong><span>60 日 {{ profile.stability.retention60 === null ? '-' : formatNumber(profile.stability.retention60*100,0)+'%' }}</span><span>只使用有效交易日持股集合</span></article></section>
    <MemberLockedResult v-if="profile && (!isAuthenticated || isMemberLockedResult(profile.percentiles))" title="同類百分位已遮隱" source="style_percentiles" />
    <section v-else-if="profile" class="profile-panel"><h2>同類百分位</h2><p>{{ profile.percentiles.comparisonGroup }}｜樣本 {{ profile.percentiles.sampleSize }}｜{{ profile.percentiles.calculationWindow }} 個交易日｜資料日 {{ profile.percentiles.dataDate }}</p><div class="percentile-row"><span>前十大集中度</span><div><i :style="{width:`${profile.percentiles.top10Concentration ?? 0}%`}"></i></div><b>{{ profile.percentiles.top10Concentration === null ? '樣本不足' : `第 ${profile.percentiles.top10Concentration} 百分位` }}</b></div><div class="percentile-row"><span>調整強度</span><div><i :style="{width:`${profile.percentiles.adjustmentIntensity ?? 0}%`}"></i></div><b>{{ profile.percentiles.adjustmentIntensity === null ? '樣本不足' : `第 ${profile.percentiles.adjustmentIntensity} 百分位` }}</b></div><small>百分位只表示與同類樣本的相對位置，不代表數值越高越好。</small></section>
    <section v-if="profile" class="profile-panel"><h2>產業輪動</h2><div class="rotation-grid"><div><b class="positive">主要加碼產業</b><span v-for="row in profile.sectorRotation.increased" :key="row.sector">{{ row.sector }} <strong :class="valueTone(row.change)">+{{ formatNumber(row.change,2) }} pp</strong></span></div><div><b class="negative">主要減碼產業</b><span v-for="row in profile.sectorRotation.decreased" :key="row.sector">{{ row.sector }} <strong :class="valueTone(row.change)">{{ formatNumber(row.change,2) }} pp</strong></span></div></div></section>
    <section v-if="profile?.limitations.length" class="limitations"><b>資料限制</b><ul><li v-for="item in profile.limitations" :key="item">{{ item }}</li></ul></section>
    <SourceDisclosure v-if="profile" :source-url="profile.etf.sourceUrl ?? undefined" note="集中度、調整強度與持股保留比例均由官方持股快照系統計算；歷史不足時不推算不存在的長期指標。" />
  </section>
</template>

<style scoped>
.style-view{display:grid;gap:16px}.style-hero{display:flex;justify-content:space-between;gap:22px;padding:27px;border:1px solid var(--theme-border);border-radius:15px;background:var(--theme-surface)}.style-hero>div>span{color:#087b72;font-size:12px;font-weight:850;letter-spacing:.13em}.style-hero h1{margin:8px 0;color:var(--theme-text-strong);font-size:32px}.style-hero p{max-width:780px;margin:0;color:var(--theme-text-muted);line-height:1.65}.style-hero label{display:grid;gap:6px;align-self:center;color:var(--theme-text-muted);font-size:12px;font-weight:760}.style-hero select{height:44px;border:1px solid var(--theme-border);border-radius:9px;background:var(--theme-surface-muted);color:var(--theme-text)}.style-labels{display:flex;align-items:center;gap:7px;flex-wrap:wrap}.style-labels span{padding:6px 10px;border-radius:999px;background:#e7f5f2;color:#087b72;font-size:12px;font-weight:800}.style-labels small{margin-left:auto;color:var(--theme-text-muted)}.style-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}.style-grid article{display:grid;gap:7px;padding:17px;border:1px solid var(--theme-border);border-radius:12px;background:var(--theme-surface)}.style-grid header{display:flex;align-items:center;gap:7px;color:var(--theme-text-muted)}.style-grid strong{color:var(--theme-text-strong);font-size:20px}.style-grid span{color:var(--theme-text-muted);font-size:12px}.profile-panel,.limitations{display:grid;gap:12px;padding:21px;border:1px solid var(--theme-border);border-radius:14px;background:var(--theme-surface)}.profile-panel h2{margin:0;color:var(--theme-text-strong)}.profile-panel>p,.profile-panel>small{margin:0;color:var(--theme-text-muted)}.percentile-row{display:grid;grid-template-columns:150px 1fr 140px;align-items:center;gap:12px}.percentile-row>div{height:10px;overflow:hidden;border-radius:999px;background:var(--theme-border)}.percentile-row i{display:block;height:100%;border-radius:999px;background:#168d84}.percentile-row b{text-align:right}.rotation-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.rotation-grid>div{display:grid;gap:7px;padding:12px;border-radius:10px;background:var(--theme-surface-muted)}.rotation-grid span{display:flex;justify-content:space-between;color:var(--theme-text-muted)}.rotation-grid strong{color:var(--theme-text-strong)}.limitations ul{margin:0;padding-left:20px;color:var(--theme-text-muted);line-height:1.7}.style-error{padding:13px;border:1px solid #f1c4c0;border-radius:10px;background:#fff4f3;color:#a8322a}.style-state{color:var(--theme-text-muted)}
@media(max-width:950px){.style-grid{grid-template-columns:repeat(2,1fr)}}
@media(max-width:650px){.style-hero{display:grid;padding:21px 17px}.style-hero h1{font-size:27px}.style-grid{grid-template-columns:1fr}.style-labels small{width:100%;margin-left:0}.percentile-row{grid-template-columns:1fr}.percentile-row b{text-align:left}.rotation-grid{grid-template-columns:1fr}}
</style>
