import type { AgentLocale } from "./agentCopy.js";

const example = {
  en: { title: "See a real research example first", task: "Compare 00981A and 00982A: holdings overlap, portfolio changes and missing data.", finding: "In the 2026-09-24 holdings snapshot, the two ETFs shared 18 holdings. The comparison covered 23 of 30 tracked Taiwan ETFs; 7 were delayed. Verify each fund and the current date in the live result.", source: "Sources: Uni-President Securities Investment Trust and Capital Investment Trust official ETF disclosures. Snapshot checked on 2026-09-29.", view: "View the research example", steps: "Choose funds → check data dates and gaps → connect MCP → download the Skill → ask your AI to explain the comparison.", role: "MCP provides the data; the Skill provides the research workflow.", install: "Installation and OAuth by tool", account: "ETF Holdings Radar uses the shared GoGoWinners account for sign-in.", cancelled: "Sign-in was cancelled. You can continue reading the public research example." },
  "zh-TW": { title: "先看真實研究範例", task: "比較 00981A 與 00982A 的持股重疊、調倉與資料缺口。", finding: "2026-09-24 持股資料日，兩檔共有 18 檔持股；當日台灣 ETF 覆蓋 23／30 檔，7 檔延遲。請在即時比較頁核對個別基金與目前資料日。", source: "來源：統一投信與群益投信官方 ETF 揭露；範例於 2026-09-29 核對。", view: "先看研究範例", steps: "選 ETF → 核對資料日與缺口 → 連接 MCP → 下載 Skill → 請 AI 說明比較結果。", role: "MCP 提供資料，Skill 提供研究流程。", install: "依工具展開安裝與 OAuth 說明", account: "ETF 持倉雷達使用 GoGoWinners 共用帳號登入。", cancelled: "已取消登入；仍可查看公開研究範例。" },
  "zh-CN": { title: "先看真实研究示例", task: "比较 00981A 与 00982A 的持股重叠、调仓及数据缺口。", finding: "2026-09-24 持股数据日，两只 ETF 共有 18 只持股；台湾 ETF 覆盖 23／30 只，7 只延迟。请在实时比较页核对当前数据日。", source: "来源：统一投信与群益投信官方 ETF 披露；示例于 2026-09-29 核对。", view: "先看研究示例", steps: "选择 ETF → 核对数据日和缺口 → 连接 MCP → 下载 Skill → 请 AI 解释比较结果。", role: "MCP 提供数据，Skill 提供研究流程。", install: "按工具展开安装及 OAuth 说明", account: "ETF 持仓雷达使用 GoGoWinners 共用账号登录。", cancelled: "已取消登录；仍可查看公开研究示例。" },
  ja: { title: "実際の調査例を見る", task: "00981A と 00982A の保有銘柄の重複、変更、欠損を比較します。", finding: "2026-09-24 の保有データでは共通銘柄は18件。台湾 ETF の対象30本中23本を確認でき、7本は遅延しています。現在のデータ日は比較ページで確認してください。", source: "出典：統一投信・群益投信の公式 ETF 開示。2026-09-29 確認。", view: "調査例を見る", steps: "ETF を選ぶ → 日付と欠損を確認 → MCP を接続 → Skill をダウンロード → AI に比較を依頼。", role: "MCP がデータを提供し、Skill が調査手順を提供します。", install: "ツール別のインストールと OAuth", account: "ETF Holdings Radar は共通の GoGoWinners アカウントでログインします。", cancelled: "ログインはキャンセルされました。公開調査例は引き続き閲覧できます。" },
  ko: { title: "실제 리서치 예시 먼저 보기", task: "00981A와 00982A의 보유 종목 중복, 변경 사항, 누락 데이터를 비교합니다.", finding: "2026-09-24 보유 데이터 기준 공통 종목은 18개입니다. 대만 ETF 30개 중 23개가 포함되었고 7개는 지연되었습니다. 현재 날짜는 비교 화면에서 확인하세요.", source: "출처: Uni-President 및 Capital Investment Trust 공식 ETF 공시. 2026-09-29 확인.", view: "리서치 예시 보기", steps: "ETF 선택 → 날짜와 누락 확인 → MCP 연결 → Skill 다운로드 → AI에 비교 요청.", role: "MCP는 데이터를 제공하고 Skill은 리서치 절차를 제공합니다.", install: "도구별 설치 및 OAuth 안내", account: "ETF Holdings Radar는 GoGoWinners 공용 계정으로 로그인합니다.", cancelled: "로그인이 취소되었습니다. 공개 리서치 예시는 계속 볼 수 있습니다." }
} satisfies Record<AgentLocale, Record<string, string>>;

export const agentSkillExample = example;
