import type { AgentLocale } from './agentCopy.js';
export const installCommands = {
  folder: 'mkdir -p ~/.agents/skills/active-etf-research',
  inspect: 'codex mcp list',
  add: 'codex mcp add active-etf --url https://active-etf-mcp.inthewins.com/api/mcp',
  login: 'codex mcp login active-etf',
  config: '[mcp_servers.active-etf]\nurl = "https://active-etf-mcp.inthewins.com/api/mcp"',
};
const en = {
  title: 'Install and verify manually', choose: 'Choose your agent', download: 'Download member Skill', login: 'Sign in above to download your Skill.',
  local: 'Codex (local Skill + MCP)', web: 'Web connector',
  steps: ['1. Install the Skill', '2. Configure the MCP connection', '3. Authorize once', '4. Verify in your AI chat'],
  save: 'Requires Codex installed on your computer. Create this folder, then save the downloaded file inside it as SKILL.md. The complete path is ~/.agents/skills/active-etf-research/SKILL.md. Start a new Codex session; restart if the Skill does not appear.',
  setup: 'First list existing connections. If active-etf already exists, verify its URL instead of adding it again. Otherwise run the add command. This may start OAuth immediately. These commands are for your local terminal; they are not executed by this page.',
  alternative: 'Without the CLI, merge this entry into ~/.codex/config.toml (do not replace the whole file), then restart Codex and authenticate through its MCP controls.',
  oauth: 'If authorization did not start during setup, run the login command. In the browser, sign in, review the named client and approve read-only research access. Return to your agent after success. Its OAuth client stores and refreshes credentials; you authorize again only when required, such as after revocation or refresh-token expiry. Never paste tokens into chat.',
  webNote: 'This is the web MCP connection route. Downloading a Skill does not install it into a web account. Only use a Skill/plugin import feature if your platform explicitly provides one; otherwise use the prompts below with the MCP connection.',
  verify: 'Ask the connected agent to run get_my_plan_usage({}). Expect remaining points and the next reset time, with no point deduction. In Codex, select $active-etf-research. Then try a holdings query. Repeating the same tool arguments within 10 minutes should not charge again.',
  checklist: ['The Skill is visible (local agent) or the web connector is enabled.', 'Browser authorization returned successfully to the agent.', 'The zero-point usage tool returned real quota and reset time.'],
  checkTitle: 'Your manual checklist (not automatic verification)',
  trouble: 'If no tools appear, enable the connection or restart the agent. If authorization expires, start login again from the agent. Share the failing step and error text without credentials.',
  reference: 'Official Codex setup documentation',
};
type Copy = { [K in keyof typeof en]: typeof en[K] };
export const agentInstall: Record<AgentLocale, Copy> = {
 en,
 'zh-TW': {
  title:'手動安裝與確認', choose:'選擇你的 Agent', download:'下載會員 Skill', login:'請先使用上方會員登入，即可下載 Skill。', local:'Codex（本機 Skill + MCP）', web:'網頁連接器',
  steps:['1. 安裝 Skill','2. 設定 MCP 連接','3. 首次 OAuth 授權','4. 回到 AI 對話確認'],
  save:'電腦需已安裝 Codex。建立下列資料夾，將下載的檔案存入並命名為 SKILL.md。完整路徑為 ~/.agents/skills/active-etf-research/SKILL.md。開啟新的 Codex 對話；若 Skill 未出現，請重新啟動 Codex。',
  setup:'先列出既有連接。若已有 active-etf，確認網址正確即可，不需重複新增；否則執行新增命令，它可能立即啟動 OAuth。這些命令由你在本機終端機執行，頁面不會代為執行。',
  alternative:'若不使用 CLI，可將下列設定合併至 ~/.codex/config.toml（保留原有內容），重新啟動 Codex，再從 MCP 設定進行授權。',
  oauth:'若設定時尚未啟動授權，執行登入命令。在瀏覽器登入會員，核對要求授權的用戶端並同意唯讀研究權限，成功後返回 Agent。OAuth 用戶端會保存與更新憑證；撤銷授權或更新憑證失效等情況才需重新授權。請勿把 token 貼到對話。',
  webNote:'這是網頁版 MCP 連接方式。下載 Skill 不會自動安裝到網頁帳號；只有平台明確提供 Skill／plugin 匯入功能時才使用該功能，否則完成 MCP 連接後直接使用下方範例。',
  verify:'請已連接的 Agent 執行 get_my_plan_usage({})，應回傳剩餘點數與下次重設時間，且不扣點。Codex 可選用 $active-etf-research。接著再試持股查詢；10 分鐘內以相同工具參數重複查詢，應不再扣點。',
  checklist:['已看到 Skill（本機 Agent）或啟用網頁連接器。','已完成瀏覽器授權並成功返回 Agent。','免費用量工具已回傳真實配額與重設時間。'],
  checkTitle:'你的手動確認清單（不是自動驗證結果）', trouble:'若沒有工具，請啟用連接或重新啟動 Agent；授權過期時請從 Agent 重新登入。若仍失敗，請提供卡住的步驟與錯誤文字，不要包含憑證。',reference:'Codex 官方設定文件',
 },
 'zh-CN': {
  title:'手动安装与确认', choose:'选择你的 Agent', download:'下载会员 Skill', login:'请先使用上方会员登录，即可下载 Skill。', local:'Codex（本地 Skill + MCP）', web:'网页连接器',
  steps:['1. 安装 Skill','2. 设置 MCP 连接','3. 首次 OAuth 授权','4. 返回 AI 对话确认'],
  save:'电脑需已安装 Codex。创建下列文件夹，将下载的文件保存为其中的 SKILL.md。完整路径为 ~/.agents/skills/active-etf-research/SKILL.md。开启新的 Codex 对话；如果 Skill 未出现，请重启 Codex。',
  setup:'先列出已有连接。如果已有 active-etf，确认地址正确即可，无需重复添加；否则运行添加命令，它可能立即启动 OAuth。这些命令由你在本地终端运行，页面不会代为执行。',
  alternative:'不使用 CLI 时，可将以下配置合并至 ~/.codex/config.toml（保留原有内容），重启 Codex，再通过 MCP 设置授权。',
  oauth:'如果设置时尚未启动授权，请运行登录命令。在浏览器登录会员，核对客户端并同意只读研究权限，成功后返回 Agent。OAuth 客户端会保存和更新凭证；撤销授权或刷新凭证失效等情况才需重新授权。请勿把 token 粘贴到对话中。',
  webNote:'这是网页版 MCP 连接方式。下载 Skill 不会自动安装到网页账号；只有平台明确提供 Skill／plugin 导入功能时才使用该功能，否则连接 MCP 后直接使用下方示例。',
  verify:'请已连接的 Agent 执行 get_my_plan_usage({})，应返回剩余点数和下次重置时间，且不扣点。Codex 可选择 $active-etf-research。然后尝试持仓查询；10 分钟内使用相同工具参数重复查询，应不再扣点。',
  checklist:['已看到 Skill（本地 Agent）或启用网页连接器。','已完成浏览器授权并成功返回 Agent。','免费用量工具已返回真实额度和重置时间。'],
  checkTitle:'你的手动确认清单（不是自动验证结果）', trouble:'如果没有工具，请启用连接或重启 Agent；授权过期时请从 Agent 重新登录。仍失败时，请提供失败步骤和错误文字，不要包含凭证。',reference:'Codex 官方设置文档',
 },
 ja: {
  title:'手動インストールと確認', choose:'Agent を選択', download:'会員用 Skill をダウンロード', login:'上の会員ログイン後に Skill をダウンロードできます。',local:'Codex（ローカル Skill + MCP）',web:'Web コネクター',
  steps:['1. Skill をインストール','2. MCP を設定','3. 初回 OAuth 認可','4. AI チャットで確認'],
  save:'パソコンに Codex が必要です。下のフォルダーを作成し、ダウンロードしたファイルを SKILL.md として保存します。完全なパスは ~/.agents/skills/active-etf-research/SKILL.md です。新しい Codex チャットを開き、表示されない場合は再起動してください。',
  setup:'既存の接続を確認します。active-etf があれば URL を確認し、重複して追加しないでください。なければ追加コマンドを実行します。OAuth がすぐ開始する場合があります。コマンドは自分の端末で実行します。このページは実行しません。',
  alternative:'CLI を使わない場合は、既存の内容を残して ~/.codex/config.toml に設定を追加し、Codex を再起動して MCP 設定から認可してください。',
  oauth:'まだ認可が開始していなければログインコマンドを実行します。ブラウザーでログインし、クライアント名を確認して読み取り専用アクセスを許可します。成功後 Agent に戻ります。OAuth クライアントが認証情報を保存・更新します。失効や更新トークンの期限切れなどの場合は再認可が必要です。トークンをチャットに貼らないでください。',
  webNote:'これは Web 版 MCP の接続手順です。Skill のダウンロードだけでは Web アカウントにインストールされません。プラットフォームが明示的に対応する場合のみ Skill／plugin のインポートを使い、それ以外は MCP 接続と下の質問例を使ってください。',
  verify:'接続済み Agent に get_my_plan_usage({}) を実行させます。ポイントを消費せず、残高と次のリセット時刻が返ることを確認してください。Codex では $active-etf-research を選択できます。その後、保有銘柄を照会します。同じ引数で10分以内に再実行しても追加消費しないことを確認します。',
  checklist:['Skill が表示されるか、Web コネクターが有効です。','ブラウザー認可を完了して Agent に戻りました。','無料の利用状況ツールが実際の残高とリセット時刻を返しました。'],checkTitle:'手動確認リスト（自動検証結果ではありません）',trouble:'ツールがなければ接続を有効にするか Agent を再起動してください。認可が期限切れなら Agent から再ログインします。問題の手順とエラー文を共有し、認証情報は含めないでください。',reference:'Codex 公式設定ドキュメント',
 },
 ko: {
  title:'수동 설치 및 확인',choose:'Agent 선택',download:'회원 Skill 다운로드',login:'위에서 회원 로그인 후 Skill을 다운로드하세요.',local:'Codex (로컬 Skill + MCP)',web:'웹 커넥터',
  steps:['1. Skill 설치','2. MCP 연결 설정','3. 최초 OAuth 승인','4. AI 대화에서 확인'],
  save:'컴퓨터에 Codex가 설치되어 있어야 합니다. 아래 폴더를 만들고 다운로드한 파일을 SKILL.md로 저장하세요. 전체 경로는 ~/.agents/skills/active-etf-research/SKILL.md입니다. 새 Codex 대화를 열고 표시되지 않으면 다시 시작하세요.',
  setup:'먼저 기존 연결을 확인하세요. active-etf가 있으면 URL을 확인하고 중복 추가하지 마세요. 없으면 추가 명령을 실행하세요. OAuth가 바로 시작될 수 있습니다. 명령은 로컬 터미널에서 직접 실행하며 이 페이지가 대신 실행하지 않습니다.',
  alternative:'CLI 없이 설정하려면 기존 내용을 유지하면서 ~/.codex/config.toml에 아래 항목을 추가하세요. Codex를 다시 시작하고 MCP 설정에서 인증하세요.',
  oauth:'아직 승인이 시작되지 않았다면 로그인 명령을 실행하세요. 브라우저에서 로그인하고 클라이언트 이름과 읽기 전용 권한을 확인한 뒤 승인하세요. 성공하면 Agent로 돌아갑니다. OAuth 클라이언트가 자격 증명을 저장하고 갱신합니다. 승인 취소나 갱신 토큰 만료 등에는 다시 승인해야 합니다. 토큰을 대화에 붙여 넣지 마세요.',
  webNote:'웹 MCP 연결 방법입니다. Skill을 다운로드해도 웹 계정에 자동 설치되지 않습니다. 플랫폼에서 Skill/plugin 가져오기를 명시적으로 지원할 때만 사용하고, 그 외에는 MCP 연결 후 아래 예시를 사용하세요.',
  verify:'연결된 Agent에 get_my_plan_usage({})를 실행해 달라고 요청하세요. 포인트 차감 없이 남은 포인트와 다음 초기화 시간이 표시되어야 합니다. Codex에서는 $active-etf-research를 선택할 수 있습니다. 이후 보유 종목을 조회하고, 10분 이내 동일한 도구 인수로 다시 조회하면 추가 차감되지 않는지 확인하세요.',
  checklist:['Skill이 표시되거나 웹 커넥터가 활성화되었습니다.','브라우저 승인을 완료하고 Agent로 돌아왔습니다.','무료 사용량 도구가 실제 잔여 한도와 초기화 시간을 반환했습니다.'],checkTitle:'수동 확인 목록 (자동 검증 결과가 아님)',trouble:'도구가 없으면 연결을 활성화하거나 Agent를 다시 시작하세요. 인증 만료 시 Agent에서 다시 로그인하세요. 문제가 발생한 단계와 오류 문구를 공유하되 자격 증명은 포함하지 마세요.',reference:'Codex 공식 설정 문서',
 },
};
export const oauthReuse: Record<AgentLocale,string> = {
 en:'After the first authorization, a compatible client stores and refreshes OAuth credentials automatically. Reauthorize if the connection is revoked or refresh credentials expire. Each AI platform needs its own authorization.',
 'zh-TW':'首次授權後，支援的用戶端會保存 OAuth 憑證並自動更新。撤銷連接或更新憑證失效時才需重新授權；不同 AI 平台需要各自授權一次。',
 'zh-CN':'首次授权后，支持的客户端会保存 OAuth 凭证并自动更新。撤销连接或刷新凭证失效时才需重新授权；不同 AI 平台需要分别授权一次。',
 ja:'初回認可後、対応クライアントが OAuth 認証情報を保存・自動更新します。接続の取り消しや更新トークンの期限切れでは再認可が必要です。各 AI プラットフォームで個別に認可してください。',
 ko:'최초 승인 후 지원 클라이언트가 OAuth 자격 증명을 저장하고 자동 갱신합니다. 연결 취소나 갱신 자격 증명 만료 시 다시 승인해야 합니다. 각 AI 플랫폼에서 별도로 승인하세요.',
};
